#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Secrets land here, not .env.local — .env.* is gitignored, and keeping prod
# values out of the dev file means `pnpm dev` can never accidentally talk to
# production Neon or send real OTP emails.
ENV_FILE=".env.production"

banner "Intake — production setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — tools and domain"
say "Checking the tools this wizard needs, then naming your domain."

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "gh authenticated — GitHub secrets will be set automatically."
else
  warn "gh missing or unauthenticated. Run 'gh auth login' in another"
  note "terminal now, or the final stage will just print what to set by hand."
  SKIPPED+=("run 'gh auth login', then re-run this wizard's last stage")
fi
command -v openssl >/dev/null 2>&1 \
  || warn "openssl missing — stage 8 can't generate secrets for you."

say ""
say "Domains. Defaults are already filled in — Enter accepts each."
note "  zone   the domain you own, shared with the portfolio site"
note "  app    where Intake is served"
[[ -n "$(_existing ZONE_DOMAIN || true)" ]] || write_env ZONE_DOMAIN "jossbleach.co.uk"
[[ -n "$(_existing APP_DOMAIN  || true)" ]] || write_env APP_DOMAIN  "intake.jossbleach.co.uk"
ask ZONE_DOMAIN "Zone (registrable domain you own):"
ask APP_DOMAIN "App hostname (where Intake is served):"
write_env ZONE_DOMAIN "$ZONE_DOMAIN"
write_env APP_DOMAIN "$APP_DOMAIN"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — account and zone"
say "A Worker can only take a custom domain when Cloudflare is authoritative"
say "for the zone. That means moving $ZONE_DOMAIN's nameservers."
say ""
warn "This is the one irreversible step in the wizard."
note "It moves ALL DNS for $ZONE_DOMAIN — including your portfolio site."
say ""
say "As checked before this wizard was written, the zone holds:"
note "  NS      ns17/ns18.domaincontrol.com   (GoDaddy)"
note "  A       $ZONE_DOMAIN -> 76.76.21.21   (Vercel, portfolio)"
note "  CNAME   www          -> cname.vercel-dns.com"
note "  MX      none — no email runs on this domain, so none can break"
say ""
say "Vercel serves fine from Cloudflare DNS. The two records just need to"
say "come across, set to DNS only."
warn "Do NOT proxy the Vercel records (grey cloud, not orange)."
note "Proxying stacks Cloudflare's CDN on Vercel's and causes cache and TLS"
note "oddities. Only the Intake Worker record wants to be proxied."
say ""
step "Before switching: open GoDaddy's DNS page and eyeball the full record"
step "list, in case something exists that a public lookup couldn't see."
open_url "https://dcc.godaddy.com/control/dnsmanagement?domainName=$ZONE_DOMAIN"
pause "Press Enter once you've seen the list."

if ! confirm "Ready to move $ZONE_DOMAIN's nameservers to Cloudflare?"; then
  SKIPPED+=("move $ZONE_DOMAIN nameservers to Cloudflare (blocks deploy)")
  warn "Skipping. Deploy will work on a workers.dev subdomain until you do."
  pause "Press Enter to continue."
else
  open_url "https://dash.cloudflare.com/sign-up"
  step "Sign up (or log in). The Free plan is enough."
  pause "Press Enter once you're in the dashboard."
  open_url "https://dash.cloudflare.com/?to=/:account/add-site"
  step "Enter $ZONE_DOMAIN and choose the Free plan."
  step "Cloudflare scans and imports the existing records. Confirm you see"
  step "the apex A to 76.76.21.21 and the www CNAME — add them if not."
  step "Set both to DNS only (click the orange cloud until it goes grey)."
  step "Copy the two nameservers it shows you (like xxx.ns.cloudflare.com)."
  pause "Press Enter once you have the two nameservers."
  say ""
  step "In GoDaddy: Nameservers → Change → 'I'll use my own nameservers'."
  step "Replace ns17/ns18.domaincontrol.com with the Cloudflare pair. Save."
  open_url "https://dcc.godaddy.com/control/dnsmanagement?domainName=$ZONE_DOMAIN"
  note "Propagation is usually minutes, but can take up to 24h."
  pause "Press Enter once GoDaddy has saved the change."
  say ""
  say "Wait for Cloudflare to show the zone as Active before deploying."
  note "Check the nameservers:  dig +short NS $ZONE_DOMAIN"
  note "Check the portfolio still resolves to Vercel:"
  note "  dig +short A $ZONE_DOMAIN     (expect 76.76.21.21)"
  note "Then load https://$ZONE_DOMAIN in a browser to be sure."
  warn "If the portfolio breaks, fix it before continuing — the rest of this"
  warn "wizard adds records to a zone that has to already be healthy."
  pause "Press Enter to continue."
  say ""
  say "While you're in the dashboard: turn on HSTS. Nothing else in the stack"
  say "sets this header, so it's Cloudflare's job or nobody's."
  open_url "https://dash.cloudflare.com/?to=/:account/$ZONE_DOMAIN/ssl-tls/edge-certificates"
  step "Enable 'Always Use HTTPS'."
  step "Enable HSTS. Sensible defaults: max-age 6 months, include subdomains,"
  step "no preload yet (preload is a one-way door — add it later once you're"
  step "sure every subdomain on $ZONE_DOMAIN is HTTPS-only)."
  note "Takes effect once the zone shows Active — fine to set now regardless."
  pause "Press Enter once set."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — account ID and API token"
say "Two credentials: one for you locally, one for CI."
say ""
step "Open the dashboard and copy your Account ID from the right-hand"
step "sidebar of the account overview (a 32-character hex string)."
open_url "https://dash.cloudflare.com/"
ask CLOUDFLARE_ACCOUNT_ID "Paste the Account ID:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

say ""
say "Now a scoped API token for GitHub Actions."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Create Custom Token."
step "Name it 'intake-ci'. Add these permissions:"
note "    Account · Workers Scripts        · Edit"
note "    Account · Workers R2 Storage     · Edit"
note "    Account · Workers KV Storage     · Edit"
note "    Account · Account Settings       · Read"
note "    Account · Hyperdrive             · Edit"
note "    Zone    · Workers Routes         · Edit"
note "    Zone    · DNS                    · Edit"
step "Scope Account Resources to your account, Zone Resources to $ZONE_DOMAIN."
step "Continue → Create Token, then copy it (shown once)."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

say ""
note "For your own machine you can skip the token and use OAuth instead:"
note "  pnpm exec alchemy login cloudflare"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Neon — API key"
say "Alchemy creates the Postgres project itself; it just needs an API key."
open_url "https://console.neon.tech/signup"
step "Sign up or log in. Don't create a project — Alchemy does that."
pause "Press Enter once you're in the console."
open_url "https://console.neon.tech/app/settings/api-keys"
step "Account settings → API keys → Create new API key."
step "Name it 'intake-alchemy' and copy the key (shown once)."
ask_secret NEON_API_KEY "Paste the Neon API key:"
write_env NEON_API_KEY "$NEON_API_KEY"
note "DATABASE_URL is not set here — Alchemy emits it from the Neon project"
note "at deploy time and binds it to the Worker."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Sentry — org, team and auth token"
say "Sentry replaces the self-hosted GlitchTip in production. Both speak the"
say "same SDK, so src/server/observability/ doesn't change — only the DSN."
open_url "https://sentry.io/signup/"
step "Sign up or log in. Note your organization slug from the URL:"
note "    https://<org-slug>.sentry.io/  or  sentry.io/organizations/<org-slug>/"
ask SENTRY_ORG "Organization slug:"
step "Settings → Teams. Copy the slug of the team that should own the project."
note "A fresh account usually has one, often '#<org-slug>'."
ask SENTRY_TEAM "Team slug:"
write_env SENTRY_ORG "$SENTRY_ORG"
write_env SENTRY_TEAM "$SENTRY_TEAM"

say ""
warn "Use a USER auth token, not an Organization token."
note "Org tokens have a fixed scope for source-map uploads and cannot create"
note "projects, which is exactly what Alchemy needs to do."
open_url "https://sentry.io/settings/account/api/auth-tokens/"
step "Create New Token. Name it 'intake-alchemy'."
step "Scopes: project:read, project:write, org:read, team:read."
step "Create, then copy the token (shown once)."
ask_secret SENTRY_AUTH_TOKEN "Paste the Sentry auth token:"
write_env SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN"
note "GLITCHTIP_DSN is not set here — Alchemy reads it off the Sentry client"
note "key it creates and binds it to the Worker."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Resend — API key"
say "Sign-in OTP emails, sent from joss@bleach.digital."
say ""
say "No DNS work here. bleach.digital is already a verified Resend sending"
say "domain — as checked before this wizard was written, it has:"
note "  MX    send.bleach.digital -> feedback-smtp.eu-west-1.amazonses.com"
note "  TXT   send.bleach.digital -> Resend SPF"
note "  TXT   resend._domainkey.bleach.digital -> DKIM"
say ""
note "That zone stays at GoDaddy. It is NOT the domain moving to Cloudflare"
note "in stage 2, and nothing in this wizard touches it."
say ""
note "Microsoft 365 keeps handling inbound mail for bleach.digital. Resend"
note "signs as d=bleach.digital and bounces via send.bleach.digital, so the"
note "apex SPF '-all' never applies to it and your DMARC policy still passes"
note "on relaxed DKIM alignment."
say ""
open_url "https://resend.com/domains"
step "Confirm bleach.digital still shows Verified. If it doesn't, fix that"
step "before continuing — OTP delivery is the whole sign-in flow."
pause "Press Enter once you've confirmed it."

say ""
open_url "https://resend.com/api-keys"
step "Create API Key → name 'intake-prod' → permission 'Sending access'."
step "Restrict it to the bleach.digital domain if the option is offered."
step "Copy it (shown once)."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"

say ""
[[ -n "$(_existing RESEND_FROM_EMAIL || true)" ]] \
  || write_env RESEND_FROM_EMAIL "Intake <joss@bleach.digital>"
ask RESEND_FROM_EMAIL "From address:"
write_env RESEND_FROM_EMAIL "$RESEND_FROM_EMAIL"
note "A reply to an OTP email lands in your Microsoft 365 inbox, which is"
note "probably what you want."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "OpenRouter — API key and credit"
say "Both logging pipelines call OpenRouter. No key has ever been provisioned"
say "for this project, so this is a genuinely new account, not a copy."
open_url "https://openrouter.ai/settings/keys"
step "Sign up or log in, then Create Key. Name it 'intake-prod'."
step "Set a credit limit on the key — a cheap blast radius if something loops."
step "Copy the key (starts sk-or-)."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter API key:"
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
say ""
open_url "https://openrouter.ai/credits"
step "Add credit. ADR 0005's picks are cheap models; £5 goes a long way."
note "The model_calls tripwire (MODEL_CALLS_TRIPWIRE_THRESHOLD) is a row-count"
note "nudge, not a spend cap — the key's own limit is the real backstop."
pause "Press Enter once credit is loaded."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Generated secrets"
say "Three values nobody hands you — generated locally, never leaving this box"
say "except into the .env file and your GitHub secrets."
say ""
note "ALCHEMY_PASSWORD     encrypts secrets inside Alchemy's state store."
note "ALCHEMY_STATE_TOKEN  bearer auth for CloudflareStateStore's own"
note "                     Durable Object worker (ADR 0008)."
note "BETTER_AUTH_SECRET   signs betterauth session cookies."
say ""
warn "Losing ALCHEMY_PASSWORD makes existing Alchemy state undecryptable."
warn "Rotating ALCHEMY_STATE_TOKEN locks out the existing state worker."
warn "Rotating BETTER_AUTH_SECRET signs every user out."
note "Put all three in your password manager before you finish this wizard."
say ""

_gen() { openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64; }

ALCHEMY_PASSWORD=$(_existing ALCHEMY_PASSWORD || true)
if [[ -n "$ALCHEMY_PASSWORD" ]]; then
  note "ALCHEMY_PASSWORD already in $ENV_FILE — keeping it."
else
  ALCHEMY_PASSWORD=$(_gen)
  say "Generated a new ALCHEMY_PASSWORD."
fi
write_env ALCHEMY_PASSWORD "$ALCHEMY_PASSWORD"

ALCHEMY_STATE_TOKEN=$(_existing ALCHEMY_STATE_TOKEN || true)
if [[ -n "$ALCHEMY_STATE_TOKEN" ]]; then
  note "ALCHEMY_STATE_TOKEN already in $ENV_FILE — keeping it."
else
  ALCHEMY_STATE_TOKEN=$(_gen)
  say "Generated a new ALCHEMY_STATE_TOKEN."
fi
write_env ALCHEMY_STATE_TOKEN "$ALCHEMY_STATE_TOKEN"

BETTER_AUTH_SECRET=$(_existing BETTER_AUTH_SECRET || true)
if [[ -n "$BETTER_AUTH_SECRET" ]]; then
  note "BETTER_AUTH_SECRET already in $ENV_FILE — keeping it."
else
  BETTER_AUTH_SECRET=$(_gen)
  say "Generated a new BETTER_AUTH_SECRET."
fi
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"

say ""
if confirm "Print all three now so you can save them to your password manager?"; then
  note "ALCHEMY_PASSWORD     $ALCHEMY_PASSWORD"
  note "ALCHEMY_STATE_TOKEN  $ALCHEMY_STATE_TOKEN"
  note "BETTER_AUTH_SECRET   $BETTER_AUTH_SECRET"
  pause "Press Enter once they're saved (this clears the screen)."
else
  note "All three are in $ENV_FILE if you want them later."
  pause "Press Enter to continue."
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Production URLs"
say "One Worker serves the SPA and /api, so the auth handler and the client"
say "share an origin — CLIENT_ORIGIN and BETTER_AUTH_URL are the same value."
write_env BETTER_AUTH_URL "https://$APP_DOMAIN"
write_env CLIENT_ORIGIN "https://$APP_DOMAIN"
note "Same-origin also means the CORS credentials dance in src/server/index.ts"
note "stops mattering in production. It still matters for local dev."
say ""
warn "This wizard can't set NODE_ENV itself — that's the deploy workflow's job"
warn "(#97). Confirm it lands as 'production' there: betterauth's own rate"
warn "limiter on OTP send/verify only turns on when NODE_ENV=production."
pause "Press Enter to continue."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "GitHub Actions secrets"
say "Mirroring everything CI needs into joss-bleach/intake."
say ""
set_secret CLOUDFLARE_API_TOKEN   "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_ACCOUNT_ID  "$CLOUDFLARE_ACCOUNT_ID"
set_secret NEON_API_KEY           "$NEON_API_KEY"
set_secret SENTRY_AUTH_TOKEN      "$SENTRY_AUTH_TOKEN"
set_secret RESEND_API_KEY         "$RESEND_API_KEY"
set_secret OPENROUTER_API_KEY     "$OPENROUTER_API_KEY"
set_secret ALCHEMY_PASSWORD       "$ALCHEMY_PASSWORD"
set_secret ALCHEMY_STATE_TOKEN    "$ALCHEMY_STATE_TOKEN"
set_secret BETTER_AUTH_SECRET     "$BETTER_AUTH_SECRET"
say ""
say "Non-secret config, as repo variables:"
set_var APP_DOMAIN        "$APP_DOMAIN"
set_var ZONE_DOMAIN       "$ZONE_DOMAIN"
set_var SENTRY_ORG        "$SENTRY_ORG"
set_var SENTRY_TEAM       "$SENTRY_TEAM"
set_var RESEND_FROM_EMAIL "$RESEND_FROM_EMAIL"
say ""
pause "Press Enter for the summary."

finish

printf '  %sNext, in the repo (not your job — see issue #97):%s\n' "$BOLD" "$RESET"
note "  - port src/server/index.ts to a Worker fetch handler"
note "  - swap pg for the Neon driver behind Hyperdrive"
note "  - write the real alchemy.run.ts (Neon, Worker, Sentry, DNS, crons)"
note "  - add the deploy job to .github/workflows"
printf '\n'
note "Then: pnpm infra:deploy"
printf '\n'
